[project]
name = "terraform-move-helper"
version = "0.0.1"
description = "CLI helper to match Terraform plan create/delete changes and generate state move commands."
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
terraform-move-helper = "terraform_move_helper:cli"

[build-system]
requires = ["setuptools>=69,<83"]
build-backend = "setuptools.build_meta"

[dependency-groups]
build = [
    "pyinstaller>=6,<7",
]
dev = [
    "pytest>=8,<10",
]

[tool.setuptools]
py-modules = ["terraform_move_helper"]
