name: Build Python Executables on Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile terraform-move-helper.py

    - name: Upload the executable to release (Linux)
      if: ${{ runner.os == 'Linux' }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/terraform-move-helper  # Linux binary
        asset_name: terraform-move-helper_linux
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload the executable to release (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/terraform-move-helper.exe  # Windows executable
        asset_name: terraform-move-helper_windows.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload the executable to release (macOS)
      if: ${{ runner.os == 'macOS' }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/terraform-move-helper  # macOS binary
        asset_name: terraform-move-helper_macos
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}
